# Generated by Django 6.1 on 2026-08-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('TO_BE_ASSIGNED', 'To Be Assigned'), ('IN_PROGRESS', 'In Progress')], default='TO_BE_ASSIGNED', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='projects', through='presales.ProjectSystem', to='presales.lightcurrentsystem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='presales_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='presales.project')),
            ],
        ),
    ]
