# Generated by Django 6.1 on 2026-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0002_project_status_project_systems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer'), ('DEVELOPER', 'Developer')], default='MEMBER', max_length=20),
        ),
    ]
