# Generated by Django 6.1 on 2026-08-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0003_alter_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsystem',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='projectsystem',
            options={'ordering': ['system__name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='systems',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
