# Generated by Django 6.1 on 2026-08-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0004_remove_projectsystem_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
