# Generated by Django 6.1 on 2026-08-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0005_project_comments_delete_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='presales.lightcurrentsystem')),
            ],
            options={
                'ordering': ['system__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_vendors', to='presales.projectsystem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_vendor_selections', to='presales.vendor')),
            ],
            options={
                'ordering': ['vendor__name'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_1_name', models.CharField(blank=True, max_length=200)),
                ('contact_1_mobile', models.CharField(blank=True, max_length=100)),
                ('contact_1_email', models.EmailField(blank=True, max_length=254)),
                ('contact_2_name', models.CharField(blank=True, max_length=200)),
                ('contact_2_mobile', models.CharField(blank=True, max_length=100)),
                ('contact_2_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='presales.vendor')),
            ],
            options={
                'ordering': ['vendor__system__name', 'vendor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_distributor_selections', to='presales.distributor')),
                ('project_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_distributors', to='presales.projectvendor')),
            ],
            options={
                'ordering': ['distributor__name'],
                'constraints': [models.UniqueConstraint(fields=('project_vendor', 'distributor'), name='unique_distributor_per_project_vendor')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('system', 'name'), name='unique_vendor_per_system'),
        ),
        migrations.AddConstraint(
            model_name='projectvendor',
            constraint=models.UniqueConstraint(fields=('project_system', 'vendor'), name='unique_vendor_per_project_system'),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('vendor', 'name'), name='unique_distributor_per_vendor'),
        ),
    ]
