# Generated by Django 6.1 on 2026-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0006_alter_project_comments_vendor_projectvendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('PRESALES', 'Presales Engineer'), ('MANAGEMENT', 'Management'), ('DEVELOPER', 'Developer')], default='PRESALES', max_length=20),
        ),
    ]
