# Generated by Django 6.1 on 2026-08-17 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0009_alter_project_presales_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presales_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
