# Generated by Django 6.1 on 2026-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0010_alter_project_presales_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('TENDERING', 'Tendering'), ('PROCUREMENT', 'Procurement')], default='TENDERING', max_length=20),
        ),
        migrations.AddField(
            model_name='projectsystem',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectsystem',
            name='offer_currency',
            field=models.CharField(blank=True, choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='projectsystem',
            name='status',
            field=models.CharField(choices=[('SENT_TO_DISTY', 'Sent to Disty'), ('QUOTATION_RECEIVED', 'Quotation Received'), ('OFFER_SUBMITTED', 'Offer Submitted')], default='SENT_TO_DISTY', max_length=30),
        ),
    ]
