# Generated by Django 6.1 on 2026-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0011_project_phase_projectsystem_offer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsystem',
            name='currency',
            field=models.CharField(blank=True, choices=[('EGP', 'EGP'), ('USD', 'USD')], default='', max_length=3),
        ),
    ]
