# Generated by Django 6.1 on 2026-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0012_projectsystem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('PRESALES_ENGINEER', 'Presales Engineer'), ('MANAGEMENT', 'Management'), ('DEVELOPER', 'Developer')], default='PRESALES_ENGINEER', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectsystem',
            name='offer_currency',
            field=models.CharField(blank=True, choices=[('EGP', 'EGP'), ('USD', 'USD')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='projectsystem',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_VL_BOQ_SPECS_DRAWINGS', 'Waiting for VL/BOQ/SPECS/DRAWINGS'), ('SENT_TO_DISTY', 'Sent to Disty'), ('QUOTATION_RECEIVED', 'Quotation Received'), ('OFFER_SUBMITTED', 'Offer Submitted')], default='WAITING_FOR_VL_BOQ_SPECS_DRAWINGS', max_length=50),
        ),
    ]
