# Generated by Django 6.1 on 2026-08-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0013_alter_person_role_alter_projectsystem_offer_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsystem',
            name='currency',
        ),
    ]
