# Generated by Django 6.1 on 2026-08-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0014_remove_projectsystem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('PRESALES', 'Presales Engineer'), ('MANAGEMENT', 'Management'), ('DEVELOPER', 'Developer')], default='PRESALES', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsystem',
            name='offer_currency',
            field=models.CharField(blank=True, choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True),
        ),
    ]
